### ISSUE TITLE
Go Away tidak bisa

### ISSUE THREAD

**Issue by winbotscript** [maxiluckiesgin/simple-bot-api-line-php#1]
Maaf Gan mau tanya, command Go Away nya kok ga bisa yah ? tolong petunjuk nya

**Comment by maxiluckiesgin** [comment]
Sudah diperbaiki dengan penambahan fungsi untuk leave group https://github.com/maxiluckiesgin/simple-bot-api-line-php/commit/31b91a16a6678090a3f2372dc629e693b543cd37

**Comment by winbotscript** [comment]
Terima kasih gan sudah bisa... tapi kok pesan sewaktu meninggalkan group tidak muncul yah gan ?

**Comment by maxiluckiesgin** [comment]
ga bisa gimana gan?

**Comment by maxiluckiesgin** [comment]
harusnya bisa gan dia cuma pake fungsi pushMessage untuk mengirim pesan, aku cek udah bener

**Comment by winbotscript** [comment]
Saya sudah coba gan tapi tetap ga bisa spt gambar terlampir, tolong bantuannya gan dan makasih sebelum nya

![screenshot_4](https://user-images.githubusercontent.com/29411717/28503534-4d81b418-7033-11e7-8ada-e63d8232d198.jpg)

**Comment by maxiluckiesgin** [comment]
coba gan https://github.com/maxiluckiesgin/simple-bot-api-line-php/commit/be8176ee762f0488598fd417494618401f6e4d01 ada unicode text yang saya hapus, mungkin itu masalahnya

**Comment by winbotscript** [comment]
Tetap ga bisa gan, tapi saya masukkan manual saja di keyword reply pada panel line bot

Gan mau tanya lagi, untuk cek MID gimana yah... jadi jika user masukkan kontak ke room maka bot akan secara otomatis keluarkan jadi diri kontak spt Display Name: Status: dan MID : 

Tolong pencerahannya dan makasih sebelum nya sudah di bantu

**Comment by maxiluckiesgin** [comment]
Dari LINE sendiri tidak menyediakan API untuk event suatu user join ke room / group. Selengkapnya bisa dibaca disini gan event apa saja yang support.
https://devdocs.line.me/en/#webhook-event-object
